version: "3.8"
services:
  niagahosterweb:
    container_name: "niagahosterweb"
    build:
      context: ${PWD}/src
      dockerfile: ${PWD}/Dockerfile
    ports:
      - '8005:80'
    working_dir: /var/www/html/
    volumes:
      - ${PWD}/src/:/var/www/html
    restart: always


